// ======================================================
// GOOGLE PREP — problem set
// Organised by the 14 patterns in "Six Months to Google",
// split into 16 sections that map 1:1 onto plan weeks.
// Separate from NeetCode 150 (lib/problems.ts) by design —
// mastery, code and notes never cross over.
// ======================================================

import type { GoogleProblem, GoogleSection, Difficulty, DesignSpec } from './types';

// p(name, difficulty, params, example?, note?)  — function-style problem
function p(name: string, difficulty: Difficulty, params: string[], example?: string, note?: string): GoogleProblem {
  return { name, difficulty, params, example, note };
}
// d(name, difficulty, class, ctorParams, methods, example?, note?) — design-and-implement problem
function d(name: string, difficulty: Difficulty, cls: string, ctor: string[], methods: DesignSpec['methods'], example?: string, note?: string): GoogleProblem {
  return { name, difficulty, params: ctor, example, design: { cls, ctor, methods }, note };
}

/** LeetCode slugs that the name→slug derivation gets wrong (or that don't exist). */
const SLUG_OVERRIDES: Record<string, string | null> = {
  'Sqrt(x)': 'sqrtx',
  'Implement Trie': 'implement-trie-prefix-tree',
  'Insert Delete GetRandom O(1)': 'insert-delete-getrandom-o1',
  'Read N Characters Given read4 II': 'read-n-characters-given-read4-ii-call-multiple-times',
  '0-1 Knapsack': null,
  'Is Graph Bipartite': 'is-graph-bipartite',
  'Encode and Decode Strings': 'encode-and-decode-strings',
};

export function leetcodeSlug(name: string): string | null {
  if (name.startsWith('Template:')) return null; // toolkit entries are ours, not LeetCode's
  if (name in SLUG_OVERRIDES) return SLUG_OVERRIDES[name];
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

export const TOOLKIT_NAMES = ['Template: MinHeap', 'Template: UnionFind', 'Template: Trie', 'Template: O(1) Queue', 'Template: Memoise', 'Template: Binary Search Bounds'];

export const GOOGLE_SECTIONS: GoogleSection[] = [
  // ───────────────────────────────────────────────── W0
  {
    id: 'toolkit',
    title: 'Toolkit — the six JavaScript templates',
    trigger: 'JS has no heap, no trie, no union-find. You bring your own — each typed from memory in under 5 minutes',
    weight: 'Very high',
    week: 0,
    problems: [
      d('Template: MinHeap', 'medium', 'MinHeap', ['compare'], [['push', ['val']], ['pop', []], ['peek', []], ['size', []]], 'compare = (a, b) => a - b, push(5), push(1), push(3), pop() -> 1, peek() -> 3, size() -> 2', '~40 lines. Array-backed: sift up on push, sift down on pop. The comparator is what turns it into a max-heap or a heap of [dist, node] tuples for Dijkstra.'),
      d('Template: UnionFind', 'medium', 'UnionFind', ['n'], [['find', ['x']], ['union', ['a', 'b']], ['connected', ['a', 'b']]], 'n = 5, union(0,1), union(1,2), connected(0,2) -> true, connected(0,3) -> false', 'Path compression in find, union by rank (or size). Return whether union actually merged — that is how you detect the redundant edge.'),
      d('Template: Trie', 'medium', 'Trie', [], [['insert', ['word']], ['search', ['word']], ['startsWith', ['prefix']]], 'insert("apple"), search("apple") -> true, search("app") -> false, startsWith("app") -> true', 'A node is { children: Map, end: boolean }. Word Search II and autocomplete are this plus DFS.'),
      d('Template: O(1) Queue', 'medium', 'Queue', [], [['push', ['x']], ['shift', []], ['peek', []], ['size', []]], 'push(1), push(2), push(3), shift() -> 1, peek() -> 2, size() -> 2', 'Array plus a head index. Array.prototype.shift() is O(n) — a BFS built on it is silently quadratic and interviewers know it.'),
      p('Template: Memoise', 'medium', ['fn'], undefined, 'Return a wrapped fn that caches on a Map keyed by the stringified args. Top-down DP is recursion + this.'),
      p('Template: Binary Search Bounds', 'medium', ['arr', 'target'], 'arr = [1,2,2,2,3], target = 2 -> [1,4]', 'Return [lowerBound, upperBound]: first index with arr[i] >= target, first index with arr[i] > target. Same loop shape, one comparison differs. Every "binary search on the answer" problem is lowerBound over a predicate.'),
    ],
  },
  // ───────────────────────────────────────────────── W1
  {
    id: 'arrays',
    title: 'Arrays, Two Pointers & Prefix Sums',
    trigger: 'Sorted array, pairs/triplets, in-place partitioning, running totals',
    weight: 'High',
    week: 1,
    problems: [
      p('Two Sum II Input Array Is Sorted', 'medium', ['numbers', 'target'], 'numbers = [2,7,11,15], target = 9 -> [1,2]'),
      p('Valid Palindrome', 'easy', ['s'], 's = "A man a plan a canal Panama" -> true'),
      p('Move Zeroes', 'easy', ['nums'], 'nums = [0,1,0,3,12] -> [1,3,12,0,0]', 'Follow-up: minimise total writes.'),
      p('Remove Duplicates from Sorted Array', 'easy', ['nums'], 'nums = [1,1,2] -> 2'),
      p('Squares of a Sorted Array', 'easy', ['nums'], 'nums = [-4,-1,0,3,10] -> [0,1,9,16,100]'),
      p('Merge Sorted Array', 'easy', ['nums1', 'm', 'nums2', 'n'], 'nums1 = [1,2,3,0,0,0], m = 3, nums2 = [2,5,6], n = 3 -> [1,2,2,3,5,6]', 'Fill from the back.'),
      p('Find Pivot Index', 'easy', ['nums'], 'nums = [1,7,3,6,5,6] -> 3'),
      p('Range Sum Query Immutable', 'easy', ['nums', 'left', 'right'], 'nums = [-2,0,3,-5,2,-1], left = 0, right = 2 -> 1'),
      p('3Sum', 'medium', ['nums'], 'nums = [-1,0,1,2,-1,-4] -> [[-1,-1,2],[-1,0,1]]', 'Dedup handling is what they watch.'),
      p('Container With Most Water', 'medium', ['height'], 'height = [1,8,6,2,5,4,8,3,7] -> 49'),
      p('Sort Colors', 'medium', ['nums'], 'nums = [2,0,2,1,1,0] -> [0,0,1,1,2,2]', 'Dutch national flag — one pass.'),
      p('Product of Array Except Self', 'medium', ['nums'], 'nums = [1,2,3,4] -> [24,12,8,6]', 'Follow-up: O(1) extra space.'),
      p('Subarray Sum Equals K', 'medium', ['nums', 'k'], 'nums = [1,1,1], k = 2 -> 2', 'Prefix sum + hash map.'),
      p('Contiguous Array', 'medium', ['nums'], 'nums = [0,1,0] -> 2'),
      p('Rotate Array', 'medium', ['nums', 'k'], 'nums = [1,2,3,4,5,6,7], k = 3 -> [5,6,7,1,2,3,4]', 'Three reversals, in place.'),
      p('Next Permutation', 'medium', ['nums'], 'nums = [1,2,3] -> [1,3,2]'),
      p('Maximum Subarray', 'medium', ['nums'], 'nums = [-2,1,-3,4,-1,2,1,-5,4] -> 6', 'Kadane; follow-up: return the indices.'),
      p('Boats to Save People', 'medium', ['people', 'limit'], 'people = [3,2,2,1], limit = 3 -> 3'),
      p('Longest Mountain in Array', 'medium', ['arr'], 'arr = [2,1,4,7,3,2,5] -> 5'),
      p('Trapping Rain Water', 'hard', ['height'], 'height = [0,1,0,2,1,0,1,3,2,1,2,1] -> 6', 'Two pointers beats the stack version in the room.'),
    ],
  },
  // ───────────────────────────────────────────────── W2
  {
    id: 'sliding-window',
    title: 'Sliding Window',
    trigger: 'Contiguous subarray or substring, "longest/shortest such that…"',
    weight: 'High',
    week: 2,
    problems: [
      p('Best Time to Buy and Sell Stock', 'easy', ['prices'], 'prices = [7,1,5,3,6,4] -> 5'),
      p('Maximum Average Subarray I', 'easy', ['nums', 'k'], 'nums = [1,12,-5,-6,50,3], k = 4 -> 12.75'),
      p('Longest Substring Without Repeating Characters', 'medium', ['s'], 's = "abcabcbb" -> 3'),
      p('Longest Repeating Character Replacement', 'medium', ['s', 'k'], 's = "AABABBA", k = 1 -> 4'),
      p('Permutation in String', 'medium', ['s1', 's2'], 's1 = "ab", s2 = "eidbaooo" -> true'),
      p('Minimum Size Subarray Sum', 'medium', ['target', 'nums'], 'target = 7, nums = [2,3,1,2,4,3] -> 2', 'Follow-up: O(n log n) with prefix sums + binary search.'),
      p('Fruit Into Baskets', 'medium', ['fruits'], 'fruits = [1,2,1] -> 3'),
      p('Max Consecutive Ones III', 'medium', ['nums', 'k'], 'nums = [1,1,1,0,0,0,1,1,1,1,0], k = 2 -> 6'),
      p('Find All Anagrams in a String', 'medium', ['s', 'p'], 's = "cbaebabacd", p = "abc" -> [0,6]'),
      p('Longest Substring with At Most K Distinct Characters', 'medium', ['s', 'k'], 's = "eceba", k = 2 -> 3', 'Google favourite — then "at most two" and "exactly K".'),
      p('Count Number of Nice Subarrays', 'medium', ['nums', 'k'], 'nums = [1,1,2,1,1], k = 3 -> 2', '"Exactly K" = atMost(K) − atMost(K−1).'),
      p('Longest Subarray of 1s After Deleting One Element', 'medium', ['nums'], 'nums = [1,1,0,1] -> 3'),
      p('Frequency of the Most Frequent Element', 'medium', ['nums', 'k'], 'nums = [1,2,4], k = 5 -> 3'),
      p('Minimum Window Substring', 'hard', ['s', 't'], 's = "ADOBECODEBANC", t = "ABC" -> "BANC"'),
      p('Sliding Window Maximum', 'hard', ['nums', 'k'], 'nums = [1,3,-1,-3,5,3,6,7], k = 3 -> [3,3,5,5,6,7]', 'Monotonic deque.'),
      p('Subarrays with K Different Integers', 'hard', ['nums', 'k'], 'nums = [1,2,1,2,3], k = 2 -> 7'),
      p('Minimum Number of K Consecutive Bit Flips', 'hard', ['nums', 'k'], 'nums = [0,1,0], k = 1 -> 2'),
      p('Substring with Concatenation of All Words', 'hard', ['s', 'words'], 's = "barfoothefoobarman", words = ["foo","bar"] -> [0,9]'),
    ],
  },
  // ───────────────────────────────────────────────── W3
  {
    id: 'hashing',
    title: 'Hashing, Frequency & Strings',
    trigger: 'Counting, seen-before, grouping, O(1) lookup needed',
    weight: 'Very high',
    week: 3,
    problems: [
      p('Two Sum', 'easy', ['nums', 'target'], 'nums = [2,7,11,15], target = 9 -> [0,1]'),
      p('Contains Duplicate', 'easy', ['nums'], 'nums = [1,2,3,1] -> true'),
      p('Valid Anagram', 'easy', ['s', 't'], 's = "anagram", t = "nagaram" -> true', 'Follow-up: Unicode input.'),
      p('First Unique Character in a String', 'easy', ['s'], 's = "leetcode" -> 0'),
      p('Isomorphic Strings', 'easy', ['s', 't'], 's = "egg", t = "add" -> true'),
      p('Word Pattern', 'easy', ['pattern', 's'], 'pattern = "abba", s = "dog cat cat dog" -> true'),
      p('Ransom Note', 'easy', ['ransomNote', 'magazine'], 'ransomNote = "aa", magazine = "aab" -> true'),
      p('Longest Palindrome', 'easy', ['s'], 's = "abccccdd" -> 7'),
      p('Longest Common Prefix', 'easy', ['strs'], 'strs = ["flower","flow","flight"] -> "fl"'),
      p('Majority Element', 'easy', ['nums'], 'nums = [2,2,1,1,1,2,2] -> 2', 'Boyer–Moore for O(1) space.'),
      d('Design HashMap', 'easy', 'MyHashMap', [], [['put', ['key', 'value']], ['get', ['key']], ['remove', ['key']]], 'put(1,1), put(2,2), get(1) -> 1, get(3) -> -1', 'Talk about load factor and resizing.'),
      d('Logger Rate Limiter', 'easy', 'Logger', [], [['shouldPrintMessage', ['timestamp', 'message']]], 'shouldPrintMessage(1,"foo") -> true, shouldPrintMessage(2,"bar") -> true, shouldPrintMessage(3,"foo") -> false', 'Follow-up: memory bound when messages never repeat.'),
      p('Group Anagrams', 'medium', ['strs'], 'strs = ["eat","tea","tan","ate","nat","bat"] -> [["bat"],["nat","tan"],["ate","eat","tea"]]', 'Count-key vs sorted-key — explain the trade-off.'),
      p('Top K Frequent Elements', 'medium', ['nums', 'k'], 'nums = [1,1,1,2,2,3], k = 2 -> [1,2]', 'Bucket sort gets O(n).'),
      p('Longest Consecutive Sequence', 'medium', ['nums'], 'nums = [100,4,200,1,3,2] -> 4'),
      p('Encode and Decode Strings', 'medium', ['strs'], 'strs = ["lint","code","love","you"] -> ["lint","code","love","you"]', 'Length-prefix framing.'),
      p('Valid Sudoku', 'medium', ['board'], undefined, 'Encode (row,val), (col,val), (box,val) in one set.'),
      d('Insert Delete GetRandom O(1)', 'medium', 'RandomizedSet', [], [['insert', ['val']], ['remove', ['val']], ['getRandom', []]], 'insert(1) -> true, remove(2) -> false, insert(2) -> true, getRandom() -> 1 or 2', 'Swap-with-last trick.'),
      d('Time Based Key-Value Store', 'medium', 'TimeMap', [], [['set', ['key', 'value', 'timestamp']], ['get', ['key', 'timestamp']]], 'set("foo","bar",1), get("foo",1) -> "bar", get("foo",3) -> "bar"'),
      p('Custom Sort String', 'medium', ['order', 's'], 'order = "cba", s = "abcd" -> "cbad"'),
      p('String Compression', 'medium', ['chars'], 'chars = ["a","a","b","b","c","c","c"] -> 6'),
      p('Subdomain Visit Count', 'medium', ['cpdomains'], 'cpdomains = ["9001 discuss.leetcode.com"] -> ["9001 discuss.leetcode.com","9001 leetcode.com","9001 com"]'),
      p('Text Justification', 'hard', ['words', 'maxWidth'], 'words = ["This","is","an","example","of","text","justification."], maxWidth = 16 -> ["This    is    an","example  of text","justification.  "]', 'Pure implementation care — a Google classic.'),
    ],
  },
  // ───────────────────────────────────────────────── W4
  {
    id: 'binary-search',
    title: 'Binary Search',
    trigger: 'Sorted input — or a monotonic answer space you can search',
    weight: 'High',
    week: 4,
    problems: [
      p('Binary Search', 'easy', ['nums', 'target'], 'nums = [-1,0,3,5,9,12], target = 9 -> 4'),
      p('Search Insert Position', 'easy', ['nums', 'target'], 'nums = [1,3,5,6], target = 5 -> 2'),
      p('Sqrt(x)', 'easy', ['x'], 'x = 8 -> 2'),
      p('First Bad Version', 'easy', ['n'], undefined, 'Minimise API calls — say it out loud.'),
      p('Search a 2D Matrix', 'medium', ['matrix', 'target'], 'matrix = [[1,3,5,7],[10,11,16,20],[23,30,34,60]], target = 3 -> true'),
      p('Search a 2D Matrix II', 'medium', ['matrix', 'target'], 'matrix = [[1,4,7,11,15],[2,5,8,12,19],[3,6,9,16,22]], target = 5 -> true', 'Staircase from top-right.'),
      p('Find First and Last Position of Element in Sorted Array', 'medium', ['nums', 'target'], 'nums = [5,7,7,8,8,10], target = 8 -> [3,4]', 'lowerBound / upperBound — your templates.'),
      p('Find Peak Element', 'medium', ['nums'], 'nums = [1,2,3,1] -> 2'),
      p('Find Minimum in Rotated Sorted Array', 'medium', ['nums'], 'nums = [3,4,5,1,2] -> 1'),
      p('Search in Rotated Sorted Array', 'medium', ['nums', 'target'], 'nums = [4,5,6,7,0,1,2], target = 0 -> 4'),
      p('Single Element in a Sorted Array', 'medium', ['nums'], 'nums = [1,1,2,3,3,4,4,8,8] -> 2', 'Parity of the index.'),
      p('Koko Eating Bananas', 'medium', ['piles', 'h'], 'piles = [3,6,7,11], h = 8 -> 4', 'Binary search on the answer — the pattern Google loves.'),
      p('Capacity To Ship Packages Within D Days', 'medium', ['weights', 'days'], 'weights = [1,2,3,4,5,6,7,8,9,10], days = 5 -> 15'),
      p('Minimum Number of Days to Make m Bouquets', 'medium', ['bloomDay', 'm', 'k'], 'bloomDay = [1,10,3,10,2], m = 3, k = 1 -> 3'),
      p('Maximum Candies Allocated to K Children', 'medium', ['candies', 'k'], 'candies = [5,8,6], k = 3 -> 5'),
      p('Kth Smallest Element in a Sorted Matrix', 'medium', ['matrix', 'k'], 'matrix = [[1,5,9],[10,11,13],[12,13,15]], k = 8 -> 13', 'Binary search on value + count ≤ mid.'),
      p('Find K Closest Elements', 'medium', ['arr', 'k', 'x'], 'arr = [1,2,3,4,5], k = 4, x = 3 -> [1,2,3,4]'),
      d('Random Pick with Weight', 'medium', 'Solution', ['w'], [['pickIndex', []]], 'w = [1,3], pickIndex() -> 1 (75% of the time)', 'Prefix sums + binary search.'),
      p('Split Array Largest Sum', 'hard', ['nums', 'k'], 'nums = [7,2,5,10,8], k = 2 -> 18'),
      p('Minimize Max Distance to Gas Station', 'hard', ['stations', 'k'], 'stations = [1,2,3,4,5,6,7,8,9,10], k = 9 -> 0.5', 'Binary search on a real-valued answer.'),
      p('Median of Two Sorted Arrays', 'hard', ['nums1', 'nums2'], 'nums1 = [1,3], nums2 = [2] -> 2.0', 'Partition search — practise the invariant aloud.'),
    ],
  },
  // ───────────────────────────────────────────────── W5
  {
    id: 'stacks',
    title: 'Stacks, Monotonic Stack & Parsing',
    trigger: 'Next/previous greater element, histograms, nested structure, expression evaluation',
    weight: 'Medium',
    week: 5,
    problems: [
      p('Valid Parentheses', 'easy', ['s'], 's = "()[]{}" -> true'),
      p('Next Greater Element I', 'easy', ['nums1', 'nums2'], 'nums1 = [4,1,2], nums2 = [1,3,4,2] -> [-1,3,-1]'),
      d('Implement Queue using Stacks', 'easy', 'MyQueue', [], [['push', ['x']], ['pop', []], ['peek', []], ['empty', []]], 'push(1), push(2), peek() -> 1, pop() -> 1, empty() -> false', 'Amortised O(1) — explain why.'),
      d('Min Stack', 'medium', 'MinStack', [], [['push', ['val']], ['pop', []], ['top', []], ['getMin', []]], 'push(-2), push(0), push(-3), getMin() -> -3, pop(), top() -> 0, getMin() -> -2'),
      p('Evaluate Reverse Polish Notation', 'medium', ['tokens'], 'tokens = ["2","1","+","3","*"] -> 9'),
      p('Daily Temperatures', 'medium', ['temperatures'], 'temperatures = [73,74,75,71,69,72,76,73] -> [1,1,4,2,1,1,0,0]'),
      p('Next Greater Element II', 'medium', ['nums'], 'nums = [1,2,1] -> [2,-1,2]', 'Circular — iterate 2n.'),
      p('Car Fleet', 'medium', ['target', 'position', 'speed'], 'target = 12, position = [10,8,0,5,3], speed = [2,4,1,1,3] -> 3'),
      p('Decode String', 'medium', ['s'], 's = "3[a]2[bc]" -> "aaabcbc"', 'Two stacks or recursion — Google asks this a lot.'),
      p('Basic Calculator II', 'medium', ['s'], 's = "3+2*2" -> 7'),
      p('Simplify Path', 'medium', ['path'], 'path = "/home//foo/" -> "/home/foo"'),
      p('Remove K Digits', 'medium', ['num', 'k'], 'num = "1432219", k = 3 -> "1219"'),
      p('Asteroid Collision', 'medium', ['asteroids'], 'asteroids = [5,10,-5] -> [5,10]'),
      p('Minimum Remove to Make Valid Parentheses', 'medium', ['s'], 's = "lee(t(c)o)de)" -> "lee(t(c)o)de"'),
      p('Exclusive Time of Functions', 'medium', ['n', 'logs'], 'n = 2, logs = ["0:start:0","1:start:2","1:end:5","0:end:6"] -> [3,4]'),
      d('Design a Stack With Increment Operation', 'medium', 'CustomStack', ['maxSize'], [['push', ['x']], ['pop', []], ['increment', ['k', 'val']]], 'maxSize = 3, push(1), push(2), increment(5, 100), pop() -> 102', 'Lazy increment for O(1).'),
      d('Online Stock Span', 'medium', 'StockSpanner', [], [['next', ['price']]], 'next(100) -> 1, next(80) -> 1, next(60) -> 1, next(70) -> 2, next(60) -> 1, next(75) -> 4'),
      p('Sum of Subarray Minimums', 'medium', ['arr'], 'arr = [3,1,2,4] -> 17', 'Previous-less and next-less-or-equal.'),
      p('Basic Calculator', 'hard', ['s'], 's = "(1+(4+5+2)-3)+(6+8)" -> 23'),
      p('Largest Rectangle in Histogram', 'hard', ['heights'], 'heights = [2,1,5,6,2,3] -> 10'),
      p('Longest Valid Parentheses', 'hard', ['s'], 's = ")()())" -> 4'),
      p('Number of Visible People in a Queue', 'hard', ['heights'], 'heights = [10,6,8,5,11,9] -> [3,1,2,1,1,0]'),
    ],
  },
  // ───────────────────────────────────────────────── W6
  {
    id: 'linked-list',
    title: 'Linked Lists & Fast/Slow Pointers',
    trigger: 'Cycle detection, midpoint, in-place reversal, K-way merge',
    weight: 'Medium',
    week: 6,
    problems: [
      p('Reverse Linked List', 'easy', ['head'], 'head = [1,2,3,4,5] -> [5,4,3,2,1]', 'Iterative and recursive — both.'),
      p('Merge Two Sorted Lists', 'easy', ['list1', 'list2'], 'list1 = [1,2,4], list2 = [1,3,4] -> [1,1,2,3,4,4]'),
      p('Linked List Cycle', 'easy', ['head'], 'head = [3,2,0,-4], pos = 1 -> true'),
      p('Middle of the Linked List', 'easy', ['head'], 'head = [1,2,3,4,5] -> [3,4,5]'),
      p('Palindrome Linked List', 'easy', ['head'], 'head = [1,2,2,1] -> true', 'Follow-up: O(1) space — reverse the second half.'),
      p('Swap Nodes in Pairs', 'easy', ['head'], 'head = [1,2,3,4] -> [2,1,4,3]'),
      p('Intersection of Two Linked Lists', 'easy', ['headA', 'headB'], undefined, 'Two-pointer switch trick.'),
      p('Reorder List', 'medium', ['head'], 'head = [1,2,3,4] -> [1,4,2,3]'),
      p('Remove Nth Node From End of List', 'medium', ['head', 'n'], 'head = [1,2,3,4,5], n = 2 -> [1,2,3,5]'),
      p('Copy List with Random Pointer', 'medium', ['head'], undefined, 'Interleave-then-split for O(1) space.'),
      p('Add Two Numbers', 'medium', ['l1', 'l2'], 'l1 = [2,4,3], l2 = [5,6,4] -> [7,0,8]'),
      p('Find the Duplicate Number', 'medium', ['nums'], 'nums = [1,3,4,2,2] -> 2', "Floyd's on an implicit linked list."),
      p('Linked List Cycle II', 'medium', ['head'], 'head = [3,2,0,-4], pos = 1 -> 2'),
      p('Odd Even Linked List', 'medium', ['head'], 'head = [1,2,3,4,5] -> [1,3,5,2,4]'),
      p('Sort List', 'medium', ['head'], 'head = [4,2,1,3] -> [1,2,3,4]', 'Merge sort, O(1) extra space bottom-up.'),
      p('Flatten a Multilevel Doubly Linked List', 'medium', ['head'], undefined),
      d('LRU Cache', 'medium', 'LRUCache', ['capacity'], [['get', ['key']], ['put', ['key', 'value']]], 'capacity = 2, put(1,1), put(2,2), get(1) -> 1, put(3,3), get(2) -> -1', 'Hash map + doubly linked list. Follow-up: thread-safe.'),
      d('Design Browser History', 'medium', 'BrowserHistory', ['homepage'], [['visit', ['url']], ['back', ['steps']], ['forward', ['steps']]], 'homepage = "leetcode.com", visit("google.com"), back(1) -> "leetcode.com"'),
      p('Merge K Sorted Lists', 'hard', ['lists'], 'lists = [[1,4,5],[1,3,4],[2,6]] -> [1,1,2,3,4,4,5,6]', 'Heap vs divide-and-conquer — compare.'),
      p('Reverse Nodes in K-Group', 'hard', ['head', 'k'], 'head = [1,2,3,4,5], k = 2 -> [2,1,4,3,5]'),
      d('LFU Cache', 'hard', 'LFUCache', ['capacity'], [['get', ['key']], ['put', ['key', 'value']]], 'capacity = 2, put(1,1), put(2,2), get(1) -> 1, put(3,3), get(2) -> -1, get(3) -> 3'),
    ],
  },
  // ───────────────────────────────────────────────── W7
  {
    id: 'heaps',
    title: 'Heaps, Top-K & Streaming',
    trigger: '"K largest", streaming median, K-way merge, scheduling',
    weight: 'High',
    week: 7,
    problems: [
      d('Kth Largest Element in a Stream', 'easy', 'KthLargest', ['k', 'nums'], [['add', ['val']]], 'k = 3, nums = [4,5,8,2], add(3) -> 4, add(5) -> 5, add(10) -> 5'),
      p('Last Stone Weight', 'easy', ['stones'], 'stones = [2,7,4,1,8,1] -> 1'),
      p('Kth Largest Element in an Array', 'medium', ['nums', 'k'], 'nums = [3,2,1,5,6,4], k = 2 -> 5', 'Heap O(n log k) vs quickselect O(n) average.'),
      p('K Closest Points to Origin', 'medium', ['points', 'k'], 'points = [[1,3],[-2,2]], k = 1 -> [[-2,2]]'),
      p('Top K Frequent Words', 'medium', ['words', 'k'], 'words = ["i","love","leetcode","i","love","coding"], k = 2 -> ["i","love"]'),
      p('Task Scheduler', 'medium', ['tasks', 'n'], 'tasks = ["A","A","A","B","B","B"], n = 2 -> 8'),
      p('Reorganize String', 'medium', ['s'], 's = "aab" -> "aba"'),
      p('Sort Characters By Frequency', 'medium', ['s'], 's = "tree" -> "eert"'),
      p('Meeting Rooms II', 'medium', ['intervals'], 'intervals = [[0,30],[5,10],[15,20]] -> 2', 'Min-heap of end times — or sweep line.'),
      p('Ugly Number II', 'medium', ['n'], 'n = 10 -> 12'),
      p('Furthest Building You Can Reach', 'medium', ['heights', 'bricks', 'ladders'], 'heights = [4,2,7,6,9,14,12], bricks = 5, ladders = 1 -> 4'),
      p('Single-Threaded CPU', 'medium', ['tasks'], 'tasks = [[1,2],[2,4],[3,2],[4,1]] -> [0,2,3,1]'),
      p('Process Tasks Using Servers', 'medium', ['servers', 'tasks'], 'servers = [3,3,2], tasks = [1,2,3,2,1,2] -> [2,2,0,2,1,2]', 'Two heaps: free and busy.'),
      d('Design Twitter', 'medium', 'Twitter', [], [['postTweet', ['userId', 'tweetId']], ['getNewsFeed', ['userId']], ['follow', ['followerId', 'followeeId']], ['unfollow', ['followerId', 'followeeId']]], 'postTweet(1,5), getNewsFeed(1) -> [5], follow(1,2), postTweet(2,6), getNewsFeed(1) -> [6,5]'),
      d('Find Median from Data Stream', 'hard', 'MedianFinder', [], [['addNum', ['num']], ['findMedian', []]], 'addNum(1), addNum(2), findMedian() -> 1.5, addNum(3), findMedian() -> 2.0', 'Two heaps. Follow-up: numbers in [0,100] → counting.'),
      p('Smallest Range Covering Elements from K Lists', 'hard', ['nums'], 'nums = [[4,10,15,24,26],[0,9,12,20],[5,18,22,30]] -> [20,24]'),
      p('Minimum Cost to Hire K Workers', 'hard', ['quality', 'wage', 'k'], 'quality = [10,20,5], wage = [70,50,30], k = 2 -> 105.0'),
      p('IPO', 'hard', ['k', 'w', 'profits', 'capital'], 'k = 2, w = 0, profits = [1,2,3], capital = [0,1,1] -> 4'),
      p('Sliding Window Median', 'hard', ['nums', 'k'], 'nums = [1,3,-1,-3,5,3,6,7], k = 3 -> [1,-1,-1,3,5,6]', 'Lazy deletion from heaps.'),
      d('Maximum Frequency Stack', 'hard', 'FreqStack', [], [['push', ['val']], ['pop', []]], 'push(5), push(7), push(5), push(7), push(4), push(5), pop() -> 5, pop() -> 7, pop() -> 5, pop() -> 4'),
    ],
  },
  // ───────────────────────────────────────────────── W9
  {
    id: 'trees',
    title: 'Binary Trees',
    trigger: 'Anything on a binary tree; DFS for paths, BFS for levels',
    weight: 'Very high',
    week: 9,
    problems: [
      p('Invert Binary Tree', 'easy', ['root'], 'root = [4,2,7,1,3,6,9] -> [4,7,2,9,6,3,1]'),
      p('Maximum Depth of Binary Tree', 'easy', ['root'], 'root = [3,9,20,null,null,15,7] -> 3', 'Recursive, then iterative BFS.'),
      p('Diameter of Binary Tree', 'easy', ['root'], 'root = [1,2,3,4,5] -> 3'),
      p('Balanced Binary Tree', 'easy', ['root'], 'root = [3,9,20,null,null,15,7] -> true'),
      p('Same Tree', 'easy', ['p', 'q'], 'p = [1,2,3], q = [1,2,3] -> true'),
      p('Symmetric Tree', 'easy', ['root'], 'root = [1,2,2,3,4,4,3] -> true'),
      p('Subtree of Another Tree', 'easy', ['root', 'subRoot'], 'root = [3,4,5,1,2], subRoot = [4,1,2] -> true'),
      p('Binary Tree Inorder Traversal', 'easy', ['root'], 'root = [1,null,2,3] -> [1,3,2]', 'Iterative with an explicit stack — Morris if asked for O(1) space.'),
      p('Count Complete Tree Nodes', 'easy', ['root'], 'root = [1,2,3,4,5,6] -> 6', 'O(log² n) using completeness.'),
      p('Binary Tree Level Order Traversal', 'medium', ['root'], 'root = [3,9,20,null,null,15,7] -> [[3],[9,20],[15,7]]'),
      p('Binary Tree Right Side View', 'medium', ['root'], 'root = [1,2,3,null,5,null,4] -> [1,3,4]'),
      p('Binary Tree Zigzag Level Order Traversal', 'medium', ['root'], 'root = [3,9,20,null,null,15,7] -> [[3],[20,9],[15,7]]'),
      p('Count Good Nodes in Binary Tree', 'medium', ['root'], 'root = [3,1,4,3,null,1,5] -> 4'),
      p('Path Sum II', 'medium', ['root', 'targetSum'], 'root = [5,4,8,11,null,13,4,7,2,null,null,5,1], targetSum = 22 -> [[5,4,11,2],[5,8,4,5]]'),
      p('Sum Root to Leaf Numbers', 'medium', ['root'], 'root = [1,2,3] -> 25'),
      p('Lowest Common Ancestor of a Binary Tree', 'medium', ['root', 'p', 'q'], 'root = [3,5,1,6,2,0,8,null,null,7,4], p = 5, q = 1 -> 3', 'Follow-up: nodes may not exist; parent pointers.'),
      p('Binary Tree Vertical Order Traversal', 'medium', ['root'], 'root = [3,9,20,null,null,15,7] -> [[9],[3,15],[20],[7]]', 'BFS with column index — a Google staple.'),
      p('Flatten Binary Tree to Linked List', 'medium', ['root'], 'root = [1,2,5,3,4,null,6] -> [1,null,2,null,3,null,4,null,5,null,6]'),
      p('Populating Next Right Pointers in Each Node', 'medium', ['root'], 'root = [1,2,3,4,5,6,7] -> [1,#,2,3,#,4,5,6,7,#]', 'O(1) space using the next pointers you just built.'),
      p('All Nodes Distance K in Binary Tree', 'medium', ['root', 'target', 'k'], 'root = [3,5,1,6,2,0,8,null,null,7,4], target = 5, k = 2 -> [7,4,1]', 'Turn the tree into a graph.'),
      p('Boundary of Binary Tree', 'medium', ['root'], 'root = [1,2,3,4,5,6,null,null,null,7,8,9,10] -> [1,2,4,7,8,9,10,6,3]'),
      p('Step-By-Step Directions From a Binary Tree Node to Another', 'medium', ['root', 'startValue', 'destValue'], 'root = [5,1,2,3,null,6,4], startValue = 3, destValue = 6 -> "UURL"'),
      p('Binary Tree Maximum Path Sum', 'hard', ['root'], 'root = [-10,9,20,null,null,15,7] -> 42', 'Return-vs-record: two different values per node.'),
    ],
  },
  // ───────────────────────────────────────────────── W10
  {
    id: 'bst',
    title: 'BSTs & Tree Construction',
    trigger: 'Ordered data in a tree; build a tree from traversals; serialise it',
    weight: 'High',
    week: 10,
    problems: [
      p('Convert Sorted Array to Binary Search Tree', 'easy', ['nums'], 'nums = [-10,-3,0,5,9] -> [0,-3,9,-10,null,5]'),
      p('Range Sum of BST', 'easy', ['root', 'low', 'high'], 'root = [10,5,15,3,7,null,18], low = 7, high = 15 -> 32', 'Prune using the BST property.'),
      p('Closest Binary Search Tree Value', 'easy', ['root', 'target'], 'root = [4,2,5,1,3], target = 3.714286 -> 4'),
      p('Validate Binary Search Tree', 'medium', ['root'], 'root = [5,1,4,null,null,3,6] -> false', 'Bounds, not just parent comparison.'),
      p('Kth Smallest Element in a BST', 'medium', ['root', 'k'], 'root = [3,1,4,null,2], k = 1 -> 1', 'Follow-up: frequent inserts — augment with subtree sizes.'),
      p('Lowest Common Ancestor of a Binary Search Tree', 'medium', ['root', 'p', 'q'], 'root = [6,2,8,0,4,7,9,null,null,3,5], p = 2, q = 8 -> 6'),
      p('Insert into a Binary Search Tree', 'medium', ['root', 'val'], 'root = [4,2,7,1,3], val = 5 -> [4,2,7,1,3,5]'),
      p('Delete Node in a BST', 'medium', ['root', 'key'], 'root = [5,3,6,2,4,null,7], key = 3 -> [5,4,6,2,null,null,7]'),
      p('Inorder Successor in BST', 'medium', ['root', 'p'], 'root = [2,1,3], p = 1 -> 2'),
      p('Trim a Binary Search Tree', 'medium', ['root', 'low', 'high'], 'root = [1,0,2], low = 1, high = 2 -> [1,null,2]'),
      p('Recover Binary Search Tree', 'medium', ['root'], 'root = [1,3,null,null,2] -> [3,1,null,null,2]'),
      p('Convert BST to Greater Tree', 'medium', ['root'], 'root = [4,1,6,0,2,5,7,null,null,null,3,null,null,null,8] -> [30,36,21,36,35,26,15,null,null,null,33,null,null,null,8]', 'Reverse inorder.'),
      p('Construct Binary Tree from Preorder and Inorder Traversal', 'medium', ['preorder', 'inorder'], 'preorder = [3,9,20,15,7], inorder = [9,3,15,20,7] -> [3,9,20,null,null,15,7]', 'Hash the inorder indices for O(n).'),
      p('Construct Binary Tree from Inorder and Postorder Traversal', 'medium', ['inorder', 'postorder'], 'inorder = [9,3,15,20,7], postorder = [9,15,7,20,3] -> [3,9,20,null,null,15,7]'),
      p('Maximum Binary Tree', 'medium', ['nums'], 'nums = [3,2,1,6,0,5] -> [6,3,5,null,2,0,null,null,1]', 'Monotonic stack gives O(n).'),
      p('Unique Binary Search Trees', 'medium', ['n'], 'n = 3 -> 5', 'Catalan numbers via DP.'),
      p('Find Leaves of Binary Tree', 'medium', ['root'], 'root = [1,2,3,4,5] -> [[4,5,3],[2],[1]]', 'Group by height — a Google favourite.'),
      p('Balance a Binary Search Tree', 'medium', ['root'], 'root = [1,null,2,null,3,null,4,null,null] -> [2,1,3,null,null,null,4]'),
      d('Binary Search Tree Iterator', 'medium', 'BSTIterator', ['root'], [['next', []], ['hasNext', []]], 'root = [7,3,15,null,null,9,20], next() -> 3, next() -> 7, hasNext() -> true', 'O(h) memory with a controlled-recursion stack.'),
      d('Serialize and Deserialize Binary Tree', 'hard', 'Codec', [], [['serialize', ['root']], ['deserialize', ['data']]], 'root = [1,2,3,null,null,4,5] -> serialize then deserialize gives the same tree', 'Preorder with null markers.'),
    ],
  },
  // ───────────────────────────────────────────────── W11
  {
    id: 'backtracking',
    title: 'Backtracking',
    trigger: 'Generate all subsets / permutations / combinations; constraint search',
    weight: 'Medium',
    week: 11,
    problems: [
      p('Subsets', 'medium', ['nums'], 'nums = [1,2,3] -> [[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]'),
      p('Subsets II', 'medium', ['nums'], 'nums = [1,2,2] -> [[],[1],[1,2],[1,2,2],[2],[2,2]]', 'Sort, then skip duplicates at the same depth.'),
      p('Permutations', 'medium', ['nums'], 'nums = [1,2,3] -> [[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]'),
      p('Permutations II', 'medium', ['nums'], 'nums = [1,1,2] -> [[1,1,2],[1,2,1],[2,1,1]]'),
      p('Combinations', 'medium', ['n', 'k'], 'n = 4, k = 2 -> [[1,2],[1,3],[1,4],[2,3],[2,4],[3,4]]'),
      p('Combination Sum', 'medium', ['candidates', 'target'], 'candidates = [2,3,6,7], target = 7 -> [[2,2,3],[7]]'),
      p('Combination Sum II', 'medium', ['candidates', 'target'], 'candidates = [10,1,2,7,6,1,5], target = 8 -> [[1,1,6],[1,2,5],[1,7],[2,6]]'),
      p('Letter Combinations of a Phone Number', 'medium', ['digits'], 'digits = "23" -> ["ad","ae","af","bd","be","bf","cd","ce","cf"]'),
      p('Generate Parentheses', 'medium', ['n'], 'n = 3 -> ["((()))","(()())","(())()","()(())","()()()"]'),
      p('Word Search', 'medium', ['board', 'word'], 'board = [["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]], word = "ABCCED" -> true', 'Mark visited in place, restore on backtrack.'),
      p('Palindrome Partitioning', 'medium', ['s'], 's = "aab" -> [["a","a","b"],["aa","b"]]'),
      p('Restore IP Addresses', 'medium', ['s'], 's = "25525511135" -> ["255.255.11.135","255.255.111.35"]'),
      p('Matchsticks to Square', 'medium', ['matchsticks'], 'matchsticks = [1,1,2,2,2] -> true', 'Sort descending for pruning.'),
      p('Partition to K Equal Sum Subsets', 'medium', ['nums', 'k'], 'nums = [4,3,2,3,5,2,1], k = 4 -> true'),
      p('Beautiful Arrangement', 'medium', ['n'], 'n = 2 -> 2'),
      p('Android Unlock Patterns', 'medium', ['m', 'n'], 'm = 1, n = 1 -> 9', 'Google classic — exploit symmetry.'),
      p('Strobogrammatic Number II', 'medium', ['n'], 'n = 2 -> ["11","69","88","96"]'),
      p('Split a String Into the Max Number of Unique Substrings', 'medium', ['s'], 's = "ababccc" -> 5'),
      p('N-Queens', 'hard', ['n'], 'n = 4 -> [[".Q..","...Q","Q...","..Q."],["..Q.","Q...","...Q",".Q.."]]', 'Sets for columns and both diagonals.'),
      p('Sudoku Solver', 'hard', ['board'], undefined, 'Pick the cell with fewest candidates.'),
      p('Expression Add Operators', 'hard', ['num', 'target'], 'num = "123", target = 6 -> ["1*2*3","1+2+3"]', 'Track last operand for multiplication.'),
    ],
  },
  // ───────────────────────────────────────────────── W12
  {
    id: 'graphs-1',
    title: 'Graphs I — BFS, DFS & Grids',
    trigger: 'Grids, connectivity, shortest path in an unweighted graph',
    weight: 'Very high',
    week: 12,
    problems: [
      p('Flood Fill', 'easy', ['image', 'sr', 'sc', 'color'], 'image = [[1,1,1],[1,1,0],[1,0,1]], sr = 1, sc = 1, color = 2 -> [[2,2,2],[2,2,0],[2,0,1]]'),
      p('Find if Path Exists in Graph', 'easy', ['n', 'edges', 'source', 'destination'], 'n = 3, edges = [[0,1],[1,2],[2,0]], source = 0, destination = 2 -> true'),
      p('Number of Islands', 'medium', ['grid'], 'grid = [["1","1","0","0","0"],["1","1","0","0","0"],["0","0","1","0","0"],["0","0","0","1","1"]] -> 3', 'Follow-up: grid too big for memory; streaming rows.'),
      p('Max Area of Island', 'medium', ['grid'], 'grid = [[0,1,1,0],[0,1,0,0],[1,0,0,1]] -> 3'),
      p('Clone Graph', 'medium', ['node'], undefined, 'Hash map old→new; BFS or DFS.'),
      p('Pacific Atlantic Water Flow', 'medium', ['heights'], 'heights = [[1,2,2,3,5],[3,2,3,4,4],[2,4,5,3,1],[6,7,1,4,5],[5,1,1,2,4]] -> [[0,4],[1,3],[1,4],[2,2],[3,0],[3,1],[4,0]]', 'Reverse-flow from the oceans.'),
      p('Surrounded Regions', 'medium', ['board'], 'board = [["X","X","X","X"],["X","O","O","X"],["X","X","O","X"],["X","O","X","X"]] -> [["X","X","X","X"],["X","X","X","X"],["X","X","X","X"],["X","O","X","X"]]'),
      p('Rotting Oranges', 'medium', ['grid'], 'grid = [[2,1,1],[1,1,0],[0,1,1]] -> 4', 'Multi-source BFS.'),
      p('Walls and Gates', 'medium', ['rooms'], 'rooms = [[2147483647,-1,0,2147483647],[2147483647,2147483647,2147483647,-1],[2147483647,-1,2147483647,-1],[0,-1,2147483647,2147483647]] -> [[3,-1,0,1],[2,2,1,-1],[1,-1,2,-1],[0,-1,3,4]]'),
      p('01 Matrix', 'medium', ['mat'], 'mat = [[0,0,0],[0,1,0],[1,1,1]] -> [[0,0,0],[0,1,0],[1,2,1]]'),
      p('Shortest Path in Binary Matrix', 'medium', ['grid'], 'grid = [[0,0,0],[1,1,0],[1,1,0]] -> 4'),
      p('Number of Connected Components in an Undirected Graph', 'medium', ['n', 'edges'], 'n = 5, edges = [[0,1],[1,2],[3,4]] -> 2'),
      p('Graph Valid Tree', 'medium', ['n', 'edges'], 'n = 5, edges = [[0,1],[0,2],[0,3],[1,4]] -> true', 'n−1 edges and connected.'),
      p('Is Graph Bipartite', 'medium', ['graph'], 'graph = [[1,3],[0,2],[1,3],[0,2]] -> true', 'Two-colouring.'),
      p('Keys and Rooms', 'medium', ['rooms'], 'rooms = [[1],[2],[3],[]] -> true'),
      p('Shortest Bridge', 'medium', ['grid'], 'grid = [[0,1],[1,0]] -> 1', 'DFS to find one island, BFS to expand it.'),
      p('Nearest Exit from Entrance in Maze', 'medium', ['maze', 'entrance'], 'maze = [["+","+",".","+"],[".",".",".","+"],["+","+","+","."]], entrance = [1,2] -> 1'),
      p('Number of Enclaves', 'medium', ['grid'], 'grid = [[0,0,0,0],[1,0,1,0],[0,1,1,0],[0,0,0,0]] -> 3'),
      p('Open the Lock', 'medium', ['deadends', 'target'], 'deadends = ["0201","0101","0102","1212","2002"], target = "0202" -> 6', 'BFS over an implicit graph.'),
      p('Snakes and Ladders', 'medium', ['board'], 'board = [[-1,-1,-1,-1,-1,-1],[-1,-1,-1,-1,-1,-1],[-1,-1,-1,-1,-1,-1],[-1,35,-1,-1,13,-1],[-1,-1,-1,-1,-1,-1],[-1,15,-1,-1,-1,-1]] -> 4'),
      p('Minimum Knight Moves', 'medium', ['x', 'y'], 'x = 2, y = 1 -> 1', 'Symmetry: search only the first quadrant.'),
      p('Word Ladder', 'hard', ['beginWord', 'endWord', 'wordList'], 'beginWord = "hit", endWord = "cog", wordList = ["hot","dot","dog","lot","log","cog"] -> 5', 'Bidirectional BFS is the follow-up.'),
      p('Bus Routes', 'hard', ['routes', 'source', 'target'], 'routes = [[1,2,7],[3,6,7]], source = 1, target = 6 -> 2', 'BFS over routes, not stops.'),
      p('Robot Room Cleaner', 'hard', ['robot'], undefined, 'The Google classic — DFS with a relative coordinate frame and a 4-turn backtrack.'),
    ],
  },
  // ───────────────────────────────────────────────── W13
  {
    id: 'graphs-2',
    title: 'Graphs II — Topological Sort, Union-Find & Shortest Paths',
    trigger: 'Dependencies / ordering in a DAG; dynamic connectivity; weighted shortest path',
    weight: 'High',
    week: 13,
    problems: [
      p('Course Schedule', 'medium', ['numCourses', 'prerequisites'], 'numCourses = 2, prerequisites = [[1,0]] -> true', "Kahn's algorithm or DFS colouring."),
      p('Course Schedule II', 'medium', ['numCourses', 'prerequisites'], 'numCourses = 4, prerequisites = [[1,0],[2,0],[3,1],[3,2]] -> [0,2,1,3]'),
      p('Parallel Courses', 'medium', ['n', 'relations'], 'n = 3, relations = [[1,3],[2,3]] -> 2', 'Longest path in a DAG.'),
      p('Minimum Height Trees', 'medium', ['n', 'edges'], 'n = 4, edges = [[1,0],[1,2],[1,3]] -> [1]', 'Peel leaves layer by layer.'),
      p('Find Eventual Safe States', 'medium', ['graph'], 'graph = [[1,2],[2,3],[5],[0],[5],[],[]] -> [2,4,5,6]'),
      p('Sequence Reconstruction', 'medium', ['nums', 'sequences'], 'nums = [1,2,3], sequences = [[1,2],[1,3],[2,3]] -> true', 'Unique topological order ⇔ queue never holds two.'),
      p('Redundant Connection', 'medium', ['edges'], 'edges = [[1,2],[1,3],[2,3]] -> [2,3]', 'Union-Find: first edge that joins an existing component.'),
      p('Number of Provinces', 'medium', ['isConnected'], 'isConnected = [[1,1,0],[1,1,0],[0,0,1]] -> 2'),
      p('Accounts Merge', 'medium', ['accounts'], 'accounts = [["John","johnsmith@mail.com","john_newyork@mail.com"],["John","johnsmith@mail.com","john00@mail.com"],["Mary","mary@mail.com"],["John","johnnybravo@mail.com"]] -> [["John","john00@mail.com","john_newyork@mail.com","johnsmith@mail.com"],["Mary","mary@mail.com"],["John","johnnybravo@mail.com"]]', 'Union-Find over emails.'),
      p('Evaluate Division', 'medium', ['equations', 'values', 'queries'], 'equations = [["a","b"],["b","c"]], values = [2.0,3.0], queries = [["a","c"],["b","a"],["a","e"],["a","a"],["x","x"]] -> [6.0,0.5,-1.0,1.0,-1.0]', 'Weighted union-find or DFS.'),
      p('Network Delay Time', 'medium', ['times', 'n', 'k'], 'times = [[2,1,1],[2,3,1],[3,4,1]], n = 4, k = 2 -> 2', 'Dijkstra with your MinHeap template.'),
      p('Cheapest Flights Within K Stops', 'medium', ['n', 'flights', 'src', 'dst', 'k'], 'n = 4, flights = [[0,1,100],[1,2,100],[2,0,100],[1,3,600],[2,3,200]], src = 0, dst = 3, k = 1 -> 700', 'Bellman-Ford with k+1 rounds.'),
      p('Path with Maximum Probability', 'medium', ['n', 'edges', 'succProb', 'start', 'end'], 'n = 3, edges = [[0,1],[1,2],[0,2]], succProb = [0.5,0.5,0.2], start = 0, end = 2 -> 0.25'),
      p('Path With Minimum Effort', 'medium', ['heights'], 'heights = [[1,2,2],[3,8,2],[5,3,5]] -> 2', 'Dijkstra on max-edge, or binary search + BFS.'),
      p('Min Cost to Connect All Points', 'medium', ['points'], 'points = [[0,0],[2,2],[3,10],[5,2],[7,0]] -> 20', "Prim's vs Kruskal's — explain both."),
      p('Alien Dictionary', 'hard', ['words'], 'words = ["wrt","wrf","er","ett","rftt"] -> "wertf"', 'Build the graph carefully: only the first differing char.'),
      p('Reconstruct Itinerary', 'hard', ['tickets'], 'tickets = [["MUC","LHR"],["JFK","MUC"],["SFO","SJC"],["LHR","SFO"]] -> ["JFK","MUC","LHR","SFO","SJC"]', 'Hierholzer — Eulerian path.'),
      p('Swim in Rising Water', 'hard', ['grid'], 'grid = [[0,2],[1,3]] -> 3'),
      p('Longest Increasing Path in a Matrix', 'hard', ['matrix'], 'matrix = [[9,9,4],[6,6,8],[2,1,1]] -> 4', 'DFS + memo — it is a DAG.'),
      p('Number of Islands II', 'hard', ['m', 'n', 'positions'], 'm = 3, n = 3, positions = [[0,0],[0,1],[1,2],[2,1]] -> [1,1,2,3]', 'Online union-find.'),
      p('Critical Connections in a Network', 'hard', ['n', 'connections'], 'n = 4, connections = [[0,1],[1,2],[2,0],[1,3]] -> [[1,3]]', "Tarjan's bridges."),
    ],
  },
  // ───────────────────────────────────────────────── W14
  {
    id: 'dp-1',
    title: 'Dynamic Programming I — One Dimension',
    trigger: 'Optimal substructure + overlapping subproblems; count / min / max of ways',
    weight: 'Very high',
    week: 14,
    problems: [
      p('Climbing Stairs', 'easy', ['n'], 'n = 3 -> 3'),
      p('Min Cost Climbing Stairs', 'easy', ['cost'], 'cost = [10,15,20] -> 15'),
      p('Counting Bits', 'easy', ['n'], 'n = 5 -> [0,1,1,2,1,2]'),
      p('House Robber', 'medium', ['nums'], 'nums = [2,7,9,3,1] -> 12'),
      p('House Robber II', 'medium', ['nums'], 'nums = [2,3,2] -> 3'),
      p('Delete and Earn', 'medium', ['nums'], 'nums = [3,4,2] -> 6', 'Reduce to House Robber.'),
      p('Longest Palindromic Substring', 'medium', ['s'], 's = "babad" -> "bab"', 'Expand around centre beats DP here.'),
      p('Palindromic Substrings', 'medium', ['s'], 's = "aaa" -> 6'),
      p('Decode Ways', 'medium', ['s'], 's = "226" -> 3', 'Edge cases: leading zeros.'),
      p('Coin Change', 'medium', ['coins', 'amount'], 'coins = [1,2,5], amount = 11 -> 3'),
      p('Combination Sum IV', 'medium', ['nums', 'target'], 'nums = [1,2,3], target = 4 -> 7', 'Order matters — loop order flips the meaning.'),
      p('Perfect Squares', 'medium', ['n'], 'n = 12 -> 3'),
      p('Maximum Product Subarray', 'medium', ['nums'], 'nums = [2,3,-2,4] -> 6', 'Track min and max.'),
      p('Maximum Sum Circular Subarray', 'medium', ['nums'], 'nums = [1,-2,3,-2] -> 3'),
      p('Word Break', 'medium', ['s', 'wordDict'], 's = "leetcode", wordDict = ["leet","code"] -> true'),
      p('Longest Increasing Subsequence', 'medium', ['nums'], 'nums = [10,9,2,5,3,7,101,18] -> 4', 'O(n log n) with patience sorting is the follow-up.'),
      p('Number of Longest Increasing Subsequence', 'medium', ['nums'], 'nums = [1,3,5,4,7] -> 2'),
      p('Partition Equal Subset Sum', 'medium', ['nums'], 'nums = [1,5,11,5] -> true', 'Subset-sum with a bitset.'),
      p('Jump Game', 'medium', ['nums'], 'nums = [2,3,1,1,4] -> true', 'Greedy furthest-reach.'),
      p('Jump Game II', 'medium', ['nums'], 'nums = [2,3,1,1,4] -> 2'),
      p('Best Time to Buy and Sell Stock with Cooldown', 'medium', ['prices'], 'prices = [1,2,3,0,2] -> 3', 'State machine.'),
      p('Paint House', 'medium', ['costs'], 'costs = [[17,2,17],[16,16,5],[14,3,19]] -> 10'),
      p('Minimum Cost For Tickets', 'medium', ['days', 'costs'], 'days = [1,4,6,7,8,20], costs = [2,7,15] -> 11'),
      p('Arithmetic Slices', 'medium', ['nums'], 'nums = [1,2,3,4] -> 3'),
    ],
  },
  // ───────────────────────────────────────────────── W15
  {
    id: 'dp-2',
    title: 'Dynamic Programming II — Two Dimensions & Intervals',
    trigger: 'Two sequences, a grid, or a choice of split point',
    weight: 'Very high',
    week: 15,
    problems: [
      p('Unique Paths', 'medium', ['m', 'n'], 'm = 3, n = 7 -> 28', 'Then O(n) space, then combinatorics.'),
      p('Unique Paths II', 'medium', ['obstacleGrid'], 'obstacleGrid = [[0,0,0],[0,1,0],[0,0,0]] -> 2'),
      p('Minimum Path Sum', 'medium', ['grid'], 'grid = [[1,3,1],[1,5,1],[4,2,1]] -> 7'),
      p('Longest Common Subsequence', 'medium', ['text1', 'text2'], 'text1 = "abcde", text2 = "ace" -> 3'),
      p('Edit Distance', 'medium', ['word1', 'word2'], 'word1 = "horse", word2 = "ros" -> 3', 'Say the recurrence before you type.'),
      p('Coin Change II', 'medium', ['amount', 'coins'], 'amount = 5, coins = [1,2,5] -> 4'),
      p('Target Sum', 'medium', ['nums', 'target'], 'nums = [1,1,1,1,1], target = 3 -> 5'),
      p('0-1 Knapsack', 'medium', ['weights', 'values', 'capacity'], 'weights = [1,3,4,5], values = [1,4,5,7], capacity = 7 -> 9', 'The template most 2-D DP reduces to.'),
      p('Interleaving String', 'medium', ['s1', 's2', 's3'], 's1 = "aabcc", s2 = "dbbca", s3 = "aadbbcbcac" -> true'),
      p('Longest Palindromic Subsequence', 'medium', ['s'], 's = "bbbab" -> 4'),
      p('Maximal Square', 'medium', ['matrix'], 'matrix = [["1","0","1","0","0"],["1","0","1","1","1"],["1","1","1","1","1"],["1","0","0","1","0"]] -> 4'),
      p('Stone Game', 'medium', ['piles'], 'piles = [5,3,4,5] -> true', 'Interval DP — game theory flavour.'),
      p('Out of Boundary Paths', 'medium', ['m', 'n', 'maxMove', 'startRow', 'startColumn'], 'm = 2, n = 2, maxMove = 2, startRow = 0, startColumn = 0 -> 6'),
      p('Distinct Subsequences', 'hard', ['s', 't'], 's = "rabbbit", t = "rabbit" -> 3'),
      p('Burst Balloons', 'hard', ['nums'], 'nums = [3,1,5,8] -> 167', 'Think "last balloon to burst" in the interval.'),
      p('Regular Expression Matching', 'hard', ['s', 'p'], 's = "aa", p = "a*" -> true'),
      p('Wildcard Matching', 'hard', ['s', 'p'], 's = "adceb", p = "*a*b" -> true'),
      p('Best Time to Buy and Sell Stock III', 'hard', ['prices'], 'prices = [3,3,5,0,0,3,1,4] -> 6'),
      p('Best Time to Buy and Sell Stock IV', 'hard', ['k', 'prices'], 'k = 2, prices = [3,2,6,5,0,3] -> 7'),
      p('Minimum Cost to Cut a Stick', 'hard', ['n', 'cuts'], 'n = 7, cuts = [1,3,4,5] -> 16'),
      p('Palindrome Partitioning II', 'hard', ['s'], 's = "aab" -> 1'),
      p('Dungeon Game', 'hard', ['dungeon'], 'dungeon = [[-2,-3,3],[-5,-10,1],[10,30,-5]] -> 7', 'DP from the bottom-right.'),
      p('Cherry Pickup', 'hard', ['grid'], 'grid = [[0,1,-1],[1,0,-1],[1,1,1]] -> 5', 'Two walkers at once.'),
      p('Strange Printer', 'hard', ['s'], 's = "aaabbb" -> 2'),
    ],
  },
  // ───────────────────────────────────────────────── W16
  {
    id: 'tries-bits-intervals',
    title: 'Tries, Bit Manipulation & Intervals',
    trigger: 'Prefix queries; parity / XOR tricks; scheduling, merging, "maximum non-overlapping"',
    weight: 'High',
    week: 16,
    problems: [
      d('Implement Trie', 'medium', 'Trie', [], [['insert', ['word']], ['search', ['word']], ['startsWith', ['prefix']]], 'insert("apple"), search("apple") -> true, search("app") -> false, startsWith("app") -> true'),
      d('Design Add and Search Words Data Structure', 'medium', 'WordDictionary', [], [['addWord', ['word']], ['search', ['word']]], 'addWord("bad"), addWord("dad"), search("pad") -> false, search(".ad") -> true'),
      p('Word Search II', 'hard', ['board', 'words'], 'board = [["o","a","a","n"],["e","t","a","e"],["i","h","k","r"],["i","f","l","v"]], words = ["oath","pea","eat","rain"] -> ["eat","oath"]', 'Trie + DFS, prune the trie as you go.'),
      p('Longest Word in Dictionary', 'medium', ['words'], 'words = ["w","wo","wor","worl","world"] -> "world"'),
      p('Replace Words', 'medium', ['dictionary', 'sentence'], 'dictionary = ["cat","bat","rat"], sentence = "the cattle was rattled by the battery" -> "the cat was rat by the bat"'),
      d('Design Search Autocomplete System', 'hard', 'AutocompleteSystem', ['sentences', 'times'], [['input', ['c']]], 'sentences = ["i love you","island","iroman","i love leetcode"], times = [5,3,2,2], input("i") -> ["i love you","island","i love leetcode"]', 'Google asks this one as a system design bridge.'),
      p('Maximum XOR of Two Numbers in an Array', 'medium', ['nums'], 'nums = [3,10,5,25,2,8] -> 28', 'Bitwise trie.'),
      p('Single Number', 'easy', ['nums'], 'nums = [4,1,2,1,2] -> 4'),
      p('Number of 1 Bits', 'easy', ['n'], 'n = 11 -> 3', "n & (n-1) — Kernighan."),
      p('Reverse Bits', 'easy', ['n'], 'n = 43261596 -> 964176192'),
      p('Missing Number', 'easy', ['nums'], 'nums = [3,0,1] -> 2'),
      p('Sum of Two Integers', 'medium', ['a', 'b'], 'a = 1, b = 2 -> 3', 'In JS mind the 32-bit coercion.'),
      p('Merge Intervals', 'medium', ['intervals'], 'intervals = [[1,3],[2,6],[8,10],[15,18]] -> [[1,6],[8,10],[15,18]]'),
      p('Insert Interval', 'medium', ['intervals', 'newInterval'], 'intervals = [[1,3],[6,9]], newInterval = [2,5] -> [[1,5],[6,9]]'),
      p('Non-overlapping Intervals', 'medium', ['intervals'], 'intervals = [[1,2],[2,3],[3,4],[1,3]] -> 1', 'Greedy by end time.'),
      p('Meeting Rooms', 'easy', ['intervals'], 'intervals = [[0,30],[5,10],[15,20]] -> false'),
      p('Interval List Intersections', 'medium', ['firstList', 'secondList'], 'firstList = [[0,2],[5,10],[13,23],[24,25]], secondList = [[1,5],[8,12],[15,24],[25,26]] -> [[1,2],[5,5],[8,10],[15,23],[24,24],[25,25]]'),
      d('My Calendar I', 'medium', 'MyCalendar', [], [['book', ['start', 'end']]], 'book(10,20) -> true, book(15,25) -> false, book(20,30) -> true', 'Follow-up: My Calendar II/III with sweep line.'),
      p('Employee Free Time', 'hard', ['schedule'], 'schedule = [[[1,2],[5,6]],[[1,3]],[[4,10]]] -> [[3,4]]'),
      p('Minimum Interval to Include Each Query', 'hard', ['intervals', 'queries'], 'intervals = [[1,4],[2,4],[3,6],[4,4]], queries = [2,3,4,5] -> [3,3,1,4]'),
      p('The Skyline Problem', 'hard', ['buildings'], 'buildings = [[2,9,10],[3,7,15],[5,12,12],[15,20,10],[19,24,8]] -> [[2,10],[3,15],[7,12],[12,0],[15,10],[20,8],[24,0]]', 'Sweep line with a max-heap.'),
      p('Gas Station', 'medium', ['gas', 'cost'], 'gas = [1,2,3,4,5], cost = [3,4,5,1,2] -> 3'),
      p('Partition Labels', 'medium', ['s'], 's = "ababcbacadefegdehijhklij" -> [9,7,8]'),
      p('Hand of Straights', 'medium', ['hand', 'groupSize'], 'hand = [1,2,3,6,2,3,4,7,8], groupSize = 3 -> true'),
      p('Merge Triplets to Form Target Triplet', 'medium', ['triplets', 'target'], 'triplets = [[2,5,3],[1,8,4],[1,7,5]], target = [2,7,5] -> true'),
      p('Valid Parenthesis String', 'medium', ['s'], 's = "(*))" -> true', 'Track a range of open counts.'),
      p('Palindrome Pairs', 'hard', ['words'], 'words = ["abcd","dcba","lls","s","sssll"] -> [[0,1],[1,0],[3,2],[2,4]]'),
    ],
  },
  // ───────────────────────────────────────────────── W19
  {
    id: 'frontend-drills',
    title: 'Frontend Drills — the vanilla-JS interview set',
    trigger: 'A Front End round asks you to implement a utility or a tiny component from scratch: closures, timers, promises, prototypes, no libraries',
    weight: 'High',
    week: 19,
    problems: [
      p('Implement Debounce', 'easy', ['fn', 'wait'], undefined, 'Return a wrapper that fires fn only after `wait` ms of silence. Follow-up: leading/trailing options, cancel().'),
      p('Implement Throttle', 'medium', ['fn', 'wait'], undefined, 'At most one call per `wait` ms; the last call in a window must still fire. Follow-up: leading vs trailing.'),
      p('Implement Memoize', 'easy', ['fn', 'resolver'], undefined, 'Cache on a key derived from the arguments; resolver overrides the key. Follow-up: cache size limit (LRU).'),
      p('Implement Curry', 'easy', ['fn'], undefined, 'Collect arguments until fn.length is reached. Follow-up: placeholder support.'),
      p('Flatten Array to Depth', 'easy', ['arr', 'depth'], 'arr = [1,[2,[3,[4]]]], depth = 2 -> [1,2,3,[4]]', 'Recursive and iterative (stack) versions. Follow-up: without recursion, and for depth = Infinity.'),
      p('Deep Equal', 'medium', ['a', 'b'], 'a = {x:[1,{y:2}]}, b = {x:[1,{y:2}]} -> true', 'Primitives, arrays, plain objects, Date, NaN, and cycles. Follow-up: what about Map/Set and prototypes?'),
      p('Deep Clone', 'medium', ['obj'], 'obj = {a:[1,{b:2}]} -> {a:[1,{b:2}]}', 'Structured copy of arrays, objects, Date, RegExp — and cyclic references via a WeakMap. Follow-up: why not JSON.parse(JSON.stringify)?'),
      p('Promise.all from Scratch', 'medium', ['promises'], undefined, 'Resolve with results in input order, reject on the first failure. Follow-up: allSettled, any, race.'),
      p('Promise Pool with Concurrency Limit', 'medium', ['tasks', 'limit'], undefined, 'tasks are functions returning promises; run at most `limit` at once, preserve result order. The real-world version of Promise.all.'),
      p('Retry with Exponential Backoff', 'medium', ['fn', 'retries', 'baseMs'], undefined, 'Retry an async fn on failure with delays base, 2×base, 4×base… plus jitter. Follow-up: only retry on certain errors; abort signal.'),
      d('Event Emitter', 'easy', 'EventEmitter', [], [['on', ['event', 'handler']], ['off', ['event', 'handler']], ['once', ['event', 'handler']], ['emit', ['event', 'payload']]], 'on("x", h), emit("x", 1), off("x", h), emit("x", 2) -> h called once', 'Map<event, Set<handler>>; once() wraps the handler and removes itself. Follow-up: return an unsubscribe function from on().'),
      d('LRU Cache (Map-based)', 'medium', 'LRUCache', ['capacity'], [['get', ['key']], ['put', ['key', 'value']]], 'capacity = 2, put(1,1), put(2,2), get(1) -> 1, put(3,3), get(2) -> -1', 'Map keeps insertion order: delete + re-set moves a key to the back. Compare with the doubly-linked-list version you wrote earlier.'),
    ],
  },
  // ───────────────────────────────────────────────── W21
  {
    id: 'google-flavour',
    title: 'Google Flavour — Design & Implement, Open-Ended, Hard',
    trigger: 'Underspecified prompts, iterators, in-memory systems, "now make it thread-safe"',
    weight: 'High',
    week: 21,
    problems: [
      d('Moving Average from Data Stream', 'easy', 'MovingAverage', ['size'], [['next', ['val']]], 'size = 3, next(1) -> 1.0, next(10) -> 5.5, next(3) -> 4.66667, next(5) -> 6.0'),
      d('Design Hit Counter', 'medium', 'HitCounter', [], [['hit', ['timestamp']], ['getHits', ['timestamp']]], 'hit(1), hit(2), hit(3), getHits(4) -> 3, hit(300), getHits(300) -> 4, getHits(301) -> 3', 'Follow-up: hits per second are huge — bucket them.'),
      d('Design Tic-Tac-Toe', 'medium', 'TicTacToe', ['n'], [['move', ['row', 'col', 'player']]], 'n = 3, move(0,0,1) -> 0, move(0,2,2) -> 0, move(2,2,1) -> 0, move(1,1,2) -> 0, move(2,0,1) -> 0, move(1,0,2) -> 0, move(2,1,1) -> 1', 'O(1) per move with row/col/diag counters.'),
      d('Design Snake Game', 'medium', 'SnakeGame', ['width', 'height', 'food'], [['move', ['direction']]], 'width = 3, height = 2, food = [[1,2],[0,1]], move("R") -> 0, move("D") -> 0, move("R") -> 1'),
      d('Peeking Iterator', 'medium', 'PeekingIterator', ['iterator'], [['peek', []], ['next', []], ['hasNext', []]], 'iterator = [1,2,3], next() -> 1, peek() -> 2, next() -> 2, next() -> 3, hasNext() -> false'),
      d('Flatten Nested List Iterator', 'medium', 'NestedIterator', ['nestedList'], [['next', []], ['hasNext', []]], 'nestedList = [[1,1],2,[1,1]] -> [1,1,2,1,1]', 'Lazy — do not flatten up front; say why.'),
      d('Zigzag Iterator', 'medium', 'ZigzagIterator', ['v1', 'v2'], [['next', []], ['hasNext', []]], 'v1 = [1,2], v2 = [3,4,5,6] -> [1,3,2,4,5,6]', 'Follow-up: k lists — queue of iterators.'),
      d('Design Underground System', 'medium', 'UndergroundSystem', [], [['checkIn', ['id', 'stationName', 't']], ['checkOut', ['id', 'stationName', 't']], ['getAverageTime', ['startStation', 'endStation']]], 'checkIn(45,"Leyton",3), checkOut(45,"Waterloo",15), getAverageTime("Leyton","Waterloo") -> 12.0'),
      d('Design a Food Rating System', 'medium', 'FoodRatings', ['foods', 'cuisines', 'ratings'], [['changeRating', ['food', 'newRating']], ['highestRated', ['cuisine']]], 'foods = ["kimchi","miso"], cuisines = ["korean","japanese"], ratings = [9,12], highestRated("korean") -> "kimchi"', 'Heap with lazy deletion.'),
      d('Stock Price Fluctuation', 'medium', 'StockPrice', [], [['update', ['timestamp', 'price']], ['current', []], ['maximum', []], ['minimum', []]], 'update(1,10), update(2,5), current() -> 5, maximum() -> 10, update(1,3), maximum() -> 5'),
      d('Random Pick Index', 'medium', 'Solution', ['nums'], [['pick', ['target']]], 'nums = [1,2,3,3,3], pick(3) -> 2, 3 or 4 with equal probability', 'Reservoir sampling — a Google staple.'),
      d('Encode and Decode TinyURL', 'medium', 'Codec', [], [['encode', ['longUrl']], ['decode', ['shortUrl']]], 'encode("https://leetcode.com/problems/design-tinyurl") -> short, decode(short) -> original', 'Bridge to the system design round.'),
      d('Detect Squares', 'medium', 'DetectSquares', [], [['add', ['point']], ['count', ['point']]], 'add([3,10]), add([11,2]), add([3,2]), count([11,10]) -> 1'),
      d('Design Text Editor', 'hard', 'TextEditor', [], [['addText', ['text']], ['deleteText', ['k']], ['cursorLeft', ['k']], ['cursorRight', ['k']]], 'addText("leetcode"), deleteText(4) -> 4, addText("practice"), cursorRight(3) -> "etpractice"', 'Two stacks around the cursor.'),
      d('Range Module', 'hard', 'RangeModule', [], [['addRange', ['left', 'right']], ['queryRange', ['left', 'right']], ['removeRange', ['left', 'right']]], 'addRange(10,20), removeRange(14,16), queryRange(10,14) -> true, queryRange(13,15) -> false'),
      d('Design In-Memory File System', 'hard', 'FileSystem', [], [['ls', ['path']], ['mkdir', ['path']], ['addContentToFile', ['filePath', 'content']], ['readContentFromFile', ['filePath']]], 'ls("/") -> [], mkdir("/a/b/c"), addContentToFile("/a/b/c/d","hello"), ls("/") -> ["a"], readContentFromFile("/a/b/c/d") -> "hello"', 'Trie of directories.'),
      d('Read N Characters Given read4 II', 'hard', 'Solution', [], [['read', ['buf', 'n']]], 'file = "abc", read(buf,1) -> 1, read(buf,2) -> 2, read(buf,1) -> 0', 'Leftover buffer between calls.'),
      p('Guess the Word', 'hard', ['words', 'master'], undefined, 'Minimax-ish elimination — the Google interview classic.'),
      p('Odd Even Jump', 'hard', ['arr'], 'arr = [10,13,12,14,15] -> 2', 'Monotonic stack over sorted indices + DP.'),
      p('Minimum Domino Rotations For Equal Row', 'medium', ['tops', 'bottoms'], 'tops = [2,1,2,4,2,2], bottoms = [5,2,6,2,3,2] -> 2'),
      p('Confusing Number II', 'hard', ['n'], 'n = 20 -> 6'),
      p('Split Array into Consecutive Subsequences', 'medium', ['nums'], 'nums = [1,2,3,3,4,5] -> true', 'Greedy with two hash maps.'),
      p('Longest String Chain', 'medium', ['words'], 'words = ["a","b","ba","bca","bda","bdca"] -> 4'),
      p('Maximum Points You Can Obtain from Cards', 'medium', ['cardPoints', 'k'], 'cardPoints = [1,2,3,4,5,6,1], k = 3 -> 12'),
      p('License Key Formatting', 'easy', ['s', 'k'], 's = "5F3Z-2e-9-w", k = 4 -> "5F3Z-2E9W"'),
      p('Candy', 'hard', ['ratings'], 'ratings = [1,0,2] -> 5', 'Two passes.'),
      p('Meeting Scheduler', 'medium', ['slots1', 'slots2', 'duration'], 'slots1 = [[10,50],[60,120],[140,210]], slots2 = [[0,15],[60,70]], duration = 8 -> [60,68]'),
      p('Bulls and Cows', 'medium', ['secret', 'guess'], 'secret = "1807", guess = "7810" -> "1A3B"'),
      p('Minimum Time Difference', 'medium', ['timePoints'], 'timePoints = ["23:59","00:00"] -> 1'),
      p('Rearrange String k Distance Apart', 'hard', ['s', 'k'], 's = "aabbcc", k = 3 -> "abcabc"'),
    ],
  },
];

// ── Derived lookups ──────────────────────────────────
export const GOOGLE_PROBLEMS: Record<string, GoogleProblem> = Object.fromEntries(
  GOOGLE_SECTIONS.flatMap(s => s.problems.map(pr => [pr.name, pr])),
);

export const GOOGLE_SECTION_OF: Record<string, GoogleSection> = Object.fromEntries(
  GOOGLE_SECTIONS.flatMap(s => s.problems.map(pr => [pr.name, s])),
);

export const GOOGLE_TOTAL = GOOGLE_SECTIONS.reduce((n, s) => n + s.problems.length, 0);

export function sectionById(id: string): GoogleSection | undefined {
  return GOOGLE_SECTIONS.find(s => s.id === id);
}

export function sectionByWeek(week: number): GoogleSection | undefined {
  return GOOGLE_SECTIONS.find(s => s.week === week);
}
